/**
 * Build /public/bird.svg from /public/reference.png using the SAME
 * sampling algorithm the live hero runs in the browser.
 *
 * No reimplementation of the threshold / shuffle loops lives in this
 * file — both come from src/geometry/birdSampling.mjs, the single
 * source of truth shared with src/geometry/birdFromImage.ts.
 *
 * Differences vs. the hero:
 *   • crop is tighter (the live hero scatters its bird in world space
 *     so stray bright pixels from the nav bar etc. are absorbed; a
 *     static og-image card can't, so we trim to the bird's bbox).
 *   • threshold + step are tuned slightly more aggressive to recover
 *     the density that the hero gets "for free" from Three.js's
 *     additive blending of overlapping particles.
 *   • RNG is seeded so the bird is byte-stable between rebuilds.
 *
 * Output is layered like text.svg's dotted typography:
 *   1. wide halo     — every dot gets a soft blurred glow
 *   2. mid dot       — every dot's mid-bright core
 *   3. bright vertex — only the brightest ~10% get a white core
 *
 * Rerun:  npm run bird     (or, indirectly, npm run og)
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { PNG } from 'pngjs';
import {
  sampleBrightPixels,
  shuffleInPlace,
} from '../src/geometry/birdSampling.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const SRC = path.join(here, '..', 'public', 'reference.png');
// Co-located with og-image.svg because librsvg refuses <image href>
// references that cross the source SVG's directory boundary.
const DST = path.join(here, '..', 'public', 'bird.svg');

// Bird's true bounding box in reference.png — established by running
// scripts/probe_bird.mjs which logs bright-pixel min/max-X per Y band.
// Right wing tip is at x=886 (1px from image right edge); the lower
// tail trail extends all the way to y=540 — much further down than
// I'd guessed before. y=540..580 is the natural gap before the about
// section, so 540 is a safe lower bound that excludes next-section
// content. There IS some chain.svg wave overlap in y≈460..540, but
// at this brightness threshold most wave pixels fall below cut.
const CROP = { x: 395, y: 75, w: 490, h: 465 };
const THRESHOLD = 0.22;
const STEP = 1;
const COUNT = 2400;
const BRIGHT_TIER = 0.62;   // top brightness fraction that gets a white core
const SEED = 0xb1d4_5eed;

// ─── 1. decode PNG to RGBA ──────────────────────────────────────────
const png = PNG.sync.read(fs.readFileSync(SRC));

// ─── 2. shared sampler ──────────────────────────────────────────────
// Same function the live hero calls in birdFromImage.ts.
const candidates = sampleBrightPixels({
  rgba: png.data,
  imageWidth: png.width,
  crop: CROP,
  threshold: THRESHOLD,
  step: STEP,
});

if (candidates.length < COUNT) {
  throw new Error(
    `Only ${candidates.length} pixels above threshold ${THRESHOLD}; need ${COUNT}.`
  );
}

// ─── 3. shared shuffle, seeded for determinism ──────────────────────
const rng = mulberry32(SEED);
shuffleInPlace(candidates, rng);
const picked = candidates.slice(0, COUNT);

// ─── 4. emit three SVG layers (halo / mid / bright) ─────────────────
const halo = [];
const mid = [];
const bright = [];

for (const p of picked) {
  const t = (p.brightness - THRESHOLD) / (1 - THRESHOLD);
  const cx = p.px.toFixed(1);
  const cy = p.py.toFixed(1);

  // Layer 1: wide halo — every dot. Big + faint, fakes additive bloom.
  const haloR = (3.2 + t * 5.2).toFixed(2);
  const haloOpacity = (0.14 + t * 0.32).toFixed(3);
  halo.push(`<circle cx="${cx}" cy="${cy}" r="${haloR}" opacity="${haloOpacity}"/>`);

  // Layer 2: mid dot — every dot, the readable silhouette stratum.
  const midR = (0.9 + t * 1.6).toFixed(2);
  const midOpacity = (0.55 + t * 0.45).toFixed(3);
  mid.push(`<circle cx="${cx}" cy="${cy}" r="${midR}" opacity="${midOpacity}"/>`);

  // Layer 3: bright vertex — only the top brightness tier.
  if (t > BRIGHT_TIER) {
    const coreR = (0.7 + (t - BRIGHT_TIER) * 2.4).toFixed(2);
    bright.push(`<circle cx="${cx}" cy="${cy}" r="${coreR}"/>`);
  }
}

const svg = `<svg xmlns="http://www.w3.org/2000/svg"
     viewBox="0 0 ${CROP.w} ${CROP.h}"
     width="${CROP.w}" height="${CROP.h}">
  <!--
    Auto-generated by scripts/build_bird_svg.mjs from public/reference.png.
    Sampling = src/geometry/birdSampling.mjs (shared with the live hero).
    DO NOT EDIT BY HAND — rerun: npm run bird
    Counts: halo+mid layers = ${picked.length} each, bright cores = ${bright.length}.
  -->
  <defs>
    <radialGradient id="haloFill" cx="50%" cy="50%" r="50%">
      <stop offset="0%"   stop-color="#9ee0ff" stop-opacity="0.85"/>
      <stop offset="60%"  stop-color="#5ec6ff" stop-opacity="0.35"/>
      <stop offset="100%" stop-color="#3fb6ff" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="midFill" cx="50%" cy="50%" r="50%">
      <stop offset="0%"   stop-color="#e8f6ff"/>
      <stop offset="60%"  stop-color="#9ee0ff"/>
      <stop offset="100%" stop-color="#4ea0ff" stop-opacity="0"/>
    </radialGradient>
    <filter id="softGlow" x="-50%" y="-50%" width="200%" height="200%">
      <feGaussianBlur stdDeviation="0.9"/>
    </filter>
  </defs>

  <g fill="url(#haloFill)" filter="url(#softGlow)">
    ${halo.join('\n    ')}
  </g>

  <g fill="url(#midFill)">
    ${mid.join('\n    ')}
  </g>

  <g fill="#ffffff">
    ${bright.join('\n    ')}
  </g>
</svg>
`;

fs.writeFileSync(DST, svg);
console.log(`Wrote ${DST}`);
console.log(`  particles : ${picked.length}`);
console.log(`  bright    : ${bright.length}`);
console.log(`  crop=${CROP.x},${CROP.y},${CROP.w}x${CROP.h}  threshold=${THRESHOLD}  step=${STEP}`);

// ─── seeded PRNG so rebuilds are byte-stable ────────────────────────
function mulberry32(seed) {
  let s = seed >>> 0;
  return function () {
    s = (s + 0x6D2B79F5) >>> 0;
    let t = s;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return (((t ^ (t >>> 14)) >>> 0) / 4294967296);
  };
}
